### PR TITLE
Fix Mozilla issue with the use of querySelectorAll and forEach

### PR DESCRIPTION
**Pull request by Mikescops**
"Click out" was not working on Mozilla.

### CODE REVIEW

**Comment by caroso1222** [comment]
Hey @Mikescops, thank you for your PR! it's very much appreciated.

Would you please tell me how can I reproduce the bug you're fixing in this PR? I tried in Firefox v53.0 MacOS on this website using the plugin and "click out" seems to work ok: https://www.ultrabox.com/principal/suite/principal/

Looking forward to hearing more about your issue.

Your help is much appreciated. Thanks again!

**Comment by Mikescops** [comment]
Hi,
Running on Debian 8  - Mozilla Firefox 45.7.0

I just tried on your website and it's not working !

BR,

**Comment by HorlogeSkynet** [comment]
Hello,

We experienced the same problem with `forEach` in another context but also against Debian and a non-ESR Firefox (stable versions unfortunately available for Debian <= 8).
The workaround was `Array.prototype.forEach` too 🤔

This has to be merged for FF users running "[old]oldstable" Debian-based systems 👍 

++

**Comment by Mikescops** [comment]
@caroso1222 will you merge that one?

**Comment by caroso1222** [comment]
Hey! sorry for the delay, I'm looking at this again now. I'm still hesitant as I don't want this script to be changing the prototype of any API as `NodeList` or `HTMLCollection `. I wonder if something like `Array.from` would work here. Need to investigate.

**Comment by caroso1222** [comment]
Merging as is. Thanks for your contribution!

**Comment by Mikescops** [comment]
You're welcome!

**Pull request merged**
